stages:
  - execute_simulation
  - cleanup

test-simulation:
  stage: execute_simulation
  image: python:3.10-slim
  before_script:
    - apt-get update && apt-get install -y wget libgl1 libglib2.0-0
  script:
    - echo "Downloading datasets..."
    - cd datasets
    - wget https://fl-dataset-storage.s3.us-east-1.amazonaws.com/datasets.tar
    - tar -xf datasets.tar
    - cd ..
    - echo "Installing uv..."
    - pip install uv
    - echo "uv installed."
    - echo "Installing dependencies with uv..."
    - uv sync --frozen --system
    - echo "Starting simulation..."
    - python src/simulation_runner.py
  artifacts:
    paths:
      - out/
    expire_in: 1 week

cleanup-output:
  stage: cleanup
  script:
    - cd out/
    - rm -rf *20*
        