export const PRESETS = {
  // SHOWCASE PRESETS - Longer runs with full convergence curves
  showcase_convergence: {
    name: 'Showcase: Full Convergence',
    subtitle: '25 rounds • 8 clients • Deep Training',
    description:
      'Premium convergence demonstration with extended training showing a complete learning curve from random initialization to high accuracy. Perfect for presentations and understanding FL dynamics.',
    estimatedTime: '8-12 minutes',
    icon: '🏆',
    tags: ['showcase', 'fundamentals', 'presentation'],
    config: {
      num_of_rounds: 25,
      num_of_clients: 8,
      num_of_malicious_clients: 0,
      aggregation_strategy_keyword: 'fedavg',
      min_fit_clients: 8,
      min_evaluate_clients: 8,
      min_available_clients: 8,
      dataset_source: 'local',
      dataset_keyword: 'femnist_iid',
      model_type: 'cnn',
      use_llm: 'false',
      remove_clients: 'false',
      begin_removing_from_round: 1,
      training_subset_fraction: 0.5,
      num_of_client_epochs: 3,
      batch_size: 32,
      training_device: 'cpu',
      attack_schedule: [],
    },
  },
  showcase_defense: {
    name: 'Showcase: Attack & Recovery',
    subtitle: '20 rounds • 6 clients • Defense Demo',
    description:
      'Dramatic visualization of Byzantine attack and successful defense. Demonstrates how Krum aggregation maintains model integrity despite sustained model poisoning attacks.',
    estimatedTime: '6-10 minutes',
    icon: '🛡️',
    tags: ['showcase', 'defense', 'presentation'],
    config: {
      num_of_rounds: 20,
      num_of_clients: 6,
      aggregation_strategy_keyword: 'krum',
      num_krum_selections: 3,
      min_fit_clients: 6,
      min_evaluate_clients: 6,
      min_available_clients: 6,
      dataset_source: 'local',
      dataset_keyword: 'femnist_iid',
      model_type: 'cnn',
      use_llm: 'false',
      remove_clients: 'true',
      begin_removing_from_round: 5,
      training_subset_fraction: 0.4,
      num_of_client_epochs: 2,
      batch_size: 32,
      training_device: 'cpu',
      preserve_dataset: 'false',
      save_attack_snapshots: 'true',
      attack_snapshot_format: 'pickle_and_visual',
      snapshot_max_samples: 5,
      attack_schedule: [
        {
          start_round: 5,
          end_round: 15,
          attack_type: 'model_poisoning',
          poison_ratio: 0.25,
          magnitude: 3.5,
          selection_strategy: 'specific',
          malicious_client_ids: [0, 1],
        },
      ],
    },
  },
  showcase_federation: {
    name: 'Showcase: Large Federation',
    subtitle: '15 rounds • 12 clients • Scaling Demo',
    description:
      'Demonstrates federated learning at scale with 12 participating clients. Shows how collaborative training improves with more participants and diverse data contributions.',
    estimatedTime: '5-8 minutes',
    icon: '🌐',
    tags: ['showcase', 'scaling', 'presentation'],
    config: {
      num_of_rounds: 15,
      num_of_clients: 12,
      num_of_malicious_clients: 0,
      aggregation_strategy_keyword: 'fedavg',
      min_fit_clients: 12,
      min_evaluate_clients: 12,
      min_available_clients: 12,
      dataset_source: 'local',
      dataset_keyword: 'femnist_iid',
      model_type: 'cnn',
      use_llm: 'false',
      remove_clients: 'false',
      begin_removing_from_round: 1,
      training_subset_fraction: 0.35,
      num_of_client_epochs: 2,
      batch_size: 32,
      training_device: 'cpu',
      attack_schedule: [],
    },
  },
  // QUICK PRESETS - Fast testing and iteration
  quickstart: {
    name: 'Baseline Convergence',
    subtitle: '10 rounds • 5 clients • FedAvg',
    description:
      'Fundamental federated learning workflow demonstrating collaborative training convergence. Ideal for understanding core FL mechanics with clean IID data distribution.',
    estimatedTime: '1-2 minutes',
    icon: '🚀',
    tags: ['beginner', 'fundamentals'],
    config: {
      num_of_rounds: 10,
      num_of_clients: 5,
      num_of_malicious_clients: 0,
      aggregation_strategy_keyword: 'fedavg',
      min_fit_clients: 5,
      min_evaluate_clients: 5,
      min_available_clients: 5,
      dataset_source: 'local',
      dataset_keyword: 'femnist_iid',
      remove_clients: 'false',
      begin_removing_from_round: 1,
      training_subset_fraction: 0.3,
      num_of_client_epochs: 1,
      batch_size: 32,
      training_device: 'cpu',
      attack_schedule: [],
    },
  },
  quick_sentiment: {
    name: 'Medical Q&A NLP',
    subtitle: '2 rounds • 2 clients • DistilBERT',
    description:
      'Federated masked language modeling on medical Q&A text with token replacement attacks. Demonstrates NLP poisoning where medical terminology is replaced with negative tokens.',
    estimatedTime: '5-10 minutes',
    icon: '🏥',
    tags: ['intermediate', 'nlp', 'medical'],
    config: {
      num_of_rounds: 2,
      num_of_clients: 2,
      aggregation_strategy_keyword: 'fedavg',
      min_fit_clients: 2,
      min_evaluate_clients: 2,
      min_available_clients: 2,
      dataset_source: 'local',
      dataset_keyword: 'medquad',
      model_type: 'transformer',
      use_llm: 'true',
      llm_model: 'distilbert-base-uncased',
      llm_finetuning: 'lora',
      llm_task: 'mlm',
      llm_chunk_size: 64,
      mlm_probability: 0.15,
      lora_rank: 4,
      lora_alpha: 32,
      lora_dropout: 0.1,
      lora_target_modules: ['q_lin', 'v_lin'],
      batch_size: 32,
      num_of_client_epochs: 1,
      training_subset_fraction: 0.005,
      training_device: 'cpu',
      remove_clients: 'false',
      begin_removing_from_round: 1,
      preserve_dataset: 'false',
      save_attack_snapshots: 'true',
      attack_snapshot_format: 'pickle_and_visual',
      snapshot_max_samples: 5,
      attack_schedule: [
        {
          start_round: 1,
          end_round: 2,
          attack_type: 'token_replacement',
          target_vocabulary: 'medical',
          replacement_strategy: 'negative',
          selection_strategy: 'specific',
          malicious_client_ids: [0],
        },
      ],
    },
  },
  convergence: {
    name: 'Non-IID Defense',
    subtitle: '8 rounds • 5 clients • PID Control',
    description:
      'Real-world heterogeneous data distribution with adaptive PID-based client removal. Tests defense effectiveness against malicious clients in challenging conditions.',
    estimatedTime: '1-2 minutes',
    icon: '📊',
    tags: ['advanced', 'data-heterogeneity'],
    config: {
      num_of_rounds: 8,
      num_of_clients: 5,
      aggregation_strategy_keyword: 'pid',
      min_fit_clients: 5,
      min_evaluate_clients: 5,
      min_available_clients: 5,
      dataset_source: 'local',
      dataset_keyword: 'femnist_niid',
      remove_clients: 'true',
      begin_removing_from_round: 2,
      training_subset_fraction: 0.3,
      training_device: 'cpu',
      num_of_client_epochs: 2,
      batch_size: 32,
      Kp: 0.8,
      Ki: 0.05,
      Kd: 0.05,
      num_std_dev: 2.2,
      preserve_dataset: 'false',
      save_attack_snapshots: 'true',
      attack_snapshot_format: 'pickle_and_visual',
      snapshot_max_samples: 5,
      attack_schedule: [
        {
          start_round: 1,
          end_round: 8,
          attack_type: 'gaussian_noise',
          target_noise_snr: 10,
          attack_ratio: 1.0,
          selection_strategy: 'specific',
          malicious_client_ids: [0, 1],
        },
      ],
    },
  },
  byzantine: {
    name: 'Byzantine Resilience',
    subtitle: '6 rounds • 4 clients • Krum',
    description:
      'Byzantine-robust aggregation defending against model poisoning attacks. Krum uses distance-based filtering to identify and exclude malicious weight updates.',
    estimatedTime: '1-2 minutes',
    icon: '⚔️',
    tags: ['intermediate', 'robust-aggregation', 'weight-poisoning'],
    config: {
      num_of_rounds: 6,
      num_of_clients: 4,
      aggregation_strategy_keyword: 'krum',
      num_krum_selections: 2,
      min_fit_clients: 4,
      min_evaluate_clients: 4,
      min_available_clients: 4,
      dataset_source: 'local',
      dataset_keyword: 'femnist_iid',
      remove_clients: 'true',
      begin_removing_from_round: 2,
      training_subset_fraction: 0.3,
      num_of_client_epochs: 1,
      batch_size: 32,
      training_device: 'cpu',
      preserve_dataset: 'false',
      save_attack_snapshots: 'true',
      attack_snapshot_format: 'pickle_and_visual',
      snapshot_max_samples: 5,
      attack_schedule: [
        {
          start_round: 2,
          end_round: 5,
          attack_type: 'model_poisoning',
          poison_ratio: 0.2,
          magnitude: 3.0,
          selection_strategy: 'specific',
          malicious_client_ids: [0, 1],
        },
      ],
    },
  },
  medical: {
    name: 'Trimmed Mean Defense',
    subtitle: '5 rounds • 4 clients • Statistical Outlier Filtering',
    description:
      'Byzantine-robust aggregation defending against weight perturbation attacks. Trimmed mean filters outlier gradients from Byzantine clients.',
    estimatedTime: '1-2 minutes',
    icon: '🎯',
    tags: ['intermediate', 'robust-aggregation', 'weight-poisoning'],
    config: {
      num_of_rounds: 5,
      num_of_clients: 4,
      aggregation_strategy_keyword: 'trimmed_mean',
      trim_ratio: 0.2,
      min_fit_clients: 4,
      min_evaluate_clients: 4,
      min_available_clients: 4,
      dataset_source: 'local',
      dataset_keyword: 'femnist_iid',
      model_type: 'cnn',
      batch_size: 32,
      remove_clients: 'false',
      begin_removing_from_round: 2,
      num_of_client_epochs: 1,
      training_subset_fraction: 0.3,
      training_device: 'cpu',
      preserve_dataset: 'false',
      save_attack_snapshots: 'true',
      attack_snapshot_format: 'pickle_and_visual',
      snapshot_max_samples: 5,
      attack_schedule: [
        {
          start_round: 1,
          end_round: 5,
          attack_type: 'byzantine_perturbation',
          perturbation_strength: 2.0,
          selection_strategy: 'specific',
          malicious_client_ids: [0, 1],
        },
      ],
    },
  },
  rfa: {
    name: 'Robust Federated Averaging',
    subtitle: '6 rounds • 4 clients • RFA',
    description:
      'Geometric median-based robust aggregation resisting gradient scaling attacks. RFA naturally filters extreme gradient magnifications without explicit detection.',
    estimatedTime: '1-2 minutes',
    icon: '🛡️',
    tags: ['intermediate', 'robust-aggregation', 'weight-poisoning'],
    config: {
      num_of_rounds: 6,
      num_of_clients: 4,
      aggregation_strategy_keyword: 'rfa',
      min_fit_clients: 4,
      min_evaluate_clients: 4,
      min_available_clients: 4,
      dataset_source: 'local',
      dataset_keyword: 'femnist_iid',
      model_type: 'cnn',
      batch_size: 32,
      remove_clients: 'false',
      begin_removing_from_round: 1,
      num_of_client_epochs: 1,
      training_subset_fraction: 0.3,
      training_device: 'cpu',
      preserve_dataset: 'false',
      save_attack_snapshots: 'true',
      attack_snapshot_format: 'pickle_and_visual',
      snapshot_max_samples: 5,
      attack_schedule: [
        {
          start_round: 2,
          end_round: 5,
          attack_type: 'gradient_scaling',
          scale_factor: 10.0,
          selection_strategy: 'specific',
          malicious_client_ids: [0, 1],
        },
      ],
    },
  },
  adaptive_defense: {
    name: 'Adaptive Multi-Phase',
    subtitle: '8 rounds • 5 clients • Dynamic Attacks',
    description:
      'Advanced defense showcasing multiple attack types: data poisoning, weight poisoning, and gradient manipulation. PID controller adapts to evolving threats.',
    estimatedTime: '1-2 minutes',
    icon: '🔄',
    tags: ['advanced', 'defense', 'weight-poisoning'],
    config: {
      num_of_rounds: 8,
      num_of_clients: 5,
      aggregation_strategy_keyword: 'pid',
      min_fit_clients: 5,
      min_evaluate_clients: 5,
      min_available_clients: 5,
      dataset_source: 'local',
      dataset_keyword: 'femnist_iid',
      remove_clients: 'true',
      begin_removing_from_round: 2,
      Kp: 1.0,
      Ki: 0.05,
      Kd: 0.05,
      num_std_dev: 2.0,
      training_subset_fraction: 0.3,
      num_of_client_epochs: 1,
      batch_size: 32,
      training_device: 'cpu',
      preserve_dataset: 'false',
      save_attack_snapshots: 'true',
      attack_snapshot_format: 'pickle_and_visual',
      snapshot_max_samples: 5,
      attack_schedule: [
        {
          start_round: 2,
          end_round: 4,
          attack_type: 'label_flipping',
          selection_strategy: 'specific',
          malicious_client_ids: [0],
        },
        {
          start_round: 5,
          end_round: 6,
          attack_type: 'model_poisoning',
          poison_ratio: 0.15,
          magnitude: 2.5,
          selection_strategy: 'specific',
          malicious_client_ids: [1, 2],
        },
        {
          start_round: 7,
          end_round: 8,
          attack_type: 'gradient_scaling',
          scale_factor: 5.0,
          selection_strategy: 'specific',
          malicious_client_ids: [3, 4],
        },
      ],
    },
  },
};
