export const PRESETS = {
  // SHOWCASE PRESETS - Longer runs with full convergence curves
  showcase_convergence: {
    name: 'Showcase: Full Convergence',
    subtitle: '30 rounds - 8 clients - Deep Training',
    description:
      'Premium convergence demonstration with extended training showing a complete learning curve from random initialization to high accuracy. Perfect for presentations and understanding FL dynamics.',
    estimatedTime: '15-20 minutes',
    icon: '🏆',
    tags: ['showcase', 'fundamentals', 'presentation'],
    config: {
      num_of_rounds: 30,
      num_of_clients: 8,
      num_of_malicious_clients: 0,
      aggregation_strategy_keyword: 'fedavg',
      min_fit_clients: 8,
      min_evaluate_clients: 8,
      min_available_clients: 8,
      dataset_source: 'local',
      dataset_keyword: 'femnist_iid',
      model_type: 'cnn',
      use_llm: false,
      remove_clients: false,
      begin_removing_from_round: 1,
      training_subset_fraction: 0.7,
      num_of_client_epochs: 5,
      batch_size: 32,
      show_plots: false,
      save_plots: true,
      save_csv: true,
      preserve_dataset: false,
      evaluate_metrics_aggregation_fn: 'weighted_average',
      attack_schedule: [],
    },
  },
  showcase_defense: {
    name: 'Showcase: Attack & Recovery',
    subtitle: '25 rounds - 8 clients - Defense Demo',
    description:
      'Dramatic visualization of Byzantine attack and successful defense. Demonstrates how Krum aggregation maintains model integrity despite sustained model poisoning attacks.',
    estimatedTime: '12-18 minutes',
    icon: '🛡️',
    tags: ['showcase', 'defense', 'presentation'],
    config: {
      num_of_rounds: 25,
      num_of_clients: 8,
      num_of_malicious_clients: 2,
      aggregation_strategy_keyword: 'krum',
      num_krum_selections: 1,
      min_fit_clients: 8,
      min_evaluate_clients: 8,
      min_available_clients: 8,
      dataset_source: 'local',
      dataset_keyword: 'femnist_iid',
      model_type: 'cnn',
      use_llm: false,
      remove_clients: true,
      strict_mode: false,
      begin_removing_from_round: 8,
      training_subset_fraction: 0.6,
      num_of_client_epochs: 4,
      batch_size: 32,
      show_plots: false,
      save_plots: true,
      save_csv: true,
      preserve_dataset: false,
      evaluate_metrics_aggregation_fn: 'weighted_average',
      save_attack_snapshots: true,
      attack_snapshot_format: 'pickle_and_visual',
      snapshot_max_samples: 6,
      attack_schedule: [
        {
          start_round: 8,
          end_round: 18,
          attack_type: 'label_flipping',
          poison_ratio: 0.15,
          selection_strategy: 'specific',
          malicious_client_ids: [0, 1],
        },
      ],
    },
  },
  showcase_federation: {
    name: 'Showcase: Large Federation',
    subtitle: '20 rounds - 16 clients - Scaling Demo',
    description:
      'Demonstrates federated learning at scale with 16 participating clients. Shows how collaborative training improves with more participants and diverse data contributions.',
    estimatedTime: '10-15 minutes',
    icon: '🌐',
    tags: ['showcase', 'scaling', 'presentation'],
    config: {
      num_of_rounds: 20,
      num_of_clients: 16,
      num_of_malicious_clients: 0,
      aggregation_strategy_keyword: 'fedavg',
      min_fit_clients: 16,
      min_evaluate_clients: 16,
      min_available_clients: 16,
      dataset_source: 'local',
      dataset_keyword: 'femnist_iid',
      model_type: 'cnn',
      use_llm: false,
      remove_clients: false,
      begin_removing_from_round: 1,
      training_subset_fraction: 0.5,
      num_of_client_epochs: 3,
      batch_size: 32,
      show_plots: false,
      save_plots: true,
      save_csv: true,
      preserve_dataset: false,
      evaluate_metrics_aggregation_fn: 'weighted_average',
      attack_schedule: [],
    },
  },
  showcase_llm: {
    name: 'Showcase: Byzantine NLP Defense',
    subtitle: '25 rounds - 5 clients - 100% Detection Rate',
    description:
      'Demonstrates Krum defense achieving 100% Byzantine detection on transformer models. Malicious token replacement attacks are identified and filtered while maintaining stable convergence throughout 25 rounds of federated DistilBERT training.',
    estimatedTime: '60-90 minutes',
    icon: '🛡️',
    tags: ['showcase', 'nlp', 'defense', 'byzantine-detection'],
    config: {
      num_of_rounds: 25,
      num_of_clients: 5,
      num_of_malicious_clients: 1,
      aggregation_strategy_keyword: 'krum',
      num_krum_selections: 1,
      min_fit_clients: 5,
      min_evaluate_clients: 5,
      min_available_clients: 5,
      dataset_source: 'local',
      dataset_keyword: 'medquad',
      model_type: 'transformer',
      use_llm: true,
      llm_model: 'distilbert-base-uncased',
      llm_finetuning: 'lora',
      llm_task: 'mlm',
      llm_chunk_size: 128,
      mlm_probability: 0.15,
      lora_rank: 16,
      lora_alpha: 32,
      lora_dropout: 0.05,
      lora_target_modules: ['q_lin', 'k_lin', 'v_lin', 'out_lin'],
      learning_rate: 1e-4,
      batch_size: 16,
      num_of_client_epochs: 5,
      training_subset_fraction: 0.25,
      remove_clients: true,
      strict_mode: false,
      begin_removing_from_round: 5,
      trust_threshold: 0.15,
      show_plots: false,
      save_plots: true,
      save_csv: true,
      preserve_dataset: false,
      evaluate_metrics_aggregation_fn: 'weighted_average',
      save_attack_snapshots: true,
      attack_snapshot_format: 'pickle_and_visual',
      snapshot_max_samples: 6,
      attack_schedule: [
        {
          start_round: 8,
          end_round: 20,
          attack_type: 'token_replacement',
          target_vocabulary: 'medical',
          replacement_strategy: 'negative',
          selection_strategy: 'specific',
          malicious_client_ids: [0],
        },
      ],
    },
  },

  // QUICK PRESETS - Fast testing and iteration
  quickstart: {
    name: 'Baseline Convergence',
    subtitle: '15 rounds - 5 clients - FedAvg',
    description:
      'Fundamental federated learning workflow demonstrating collaborative training convergence. Ideal for understanding core FL mechanics with clean IID data distribution.',
    estimatedTime: '2-3 minutes',
    icon: '🚀',
    tags: ['beginner', 'fundamentals'],
    config: {
      num_of_rounds: 15,
      num_of_clients: 5,
      num_of_malicious_clients: 0,
      aggregation_strategy_keyword: 'fedavg',
      min_fit_clients: 5,
      min_evaluate_clients: 5,
      min_available_clients: 5,
      dataset_source: 'local',
      dataset_keyword: 'femnist_iid',
      model_type: 'cnn',
      use_llm: false,
      remove_clients: false,
      begin_removing_from_round: 1,
      training_subset_fraction: 0.5,
      num_of_client_epochs: 2,
      batch_size: 32,
      show_plots: false,
      save_plots: true,
      save_csv: true,
      preserve_dataset: false,
      evaluate_metrics_aggregation_fn: 'weighted_average',
      attack_schedule: [],
    },
  },
  quick_sentiment: {
    name: 'NLP Attack Visualization',
    subtitle: '8 rounds - 2 clients - Token Poisoning Demo',
    description:
      'Visualizes token replacement attacks on medical NLP. Captures attack snapshots showing how malicious clients corrupt medical terminology, with detailed poisoning pattern analysis for federated transformer training.',
    estimatedTime: '8-12 minutes',
    icon: '🔬',
    tags: ['intermediate', 'nlp', 'attack-analysis', 'visualization'],
    config: {
      num_of_rounds: 8,
      num_of_clients: 2,
      num_of_malicious_clients: 1,
      aggregation_strategy_keyword: 'fedavg',
      min_fit_clients: 2,
      min_evaluate_clients: 2,
      min_available_clients: 2,
      dataset_source: 'local',
      dataset_keyword: 'medquad',
      model_type: 'transformer',
      use_llm: true,
      llm_model: 'distilbert-base-uncased',
      llm_finetuning: 'lora',
      llm_task: 'mlm',
      llm_chunk_size: 64,
      mlm_probability: 0.15,
      lora_rank: 8,
      lora_alpha: 16,
      lora_dropout: 0.1,
      lora_target_modules: ['q_lin', 'v_lin'],
      learning_rate: 1e-4,
      batch_size: 32,
      num_of_client_epochs: 2,
      training_subset_fraction: 0.2,
      remove_clients: false,
      begin_removing_from_round: 1,
      show_plots: false,
      save_plots: true,
      save_csv: true,
      preserve_dataset: false,
      evaluate_metrics_aggregation_fn: 'weighted_average',
      save_attack_snapshots: true,
      attack_snapshot_format: 'pickle_and_visual',
      snapshot_max_samples: 6,
      attack_schedule: [
        {
          start_round: 1,
          end_round: 8,
          attack_type: 'token_replacement',
          target_vocabulary: 'medical',
          replacement_strategy: 'negative',
          selection_strategy: 'specific',
          malicious_client_ids: [0],
        },
      ],
    },
  },
  convergence: {
    name: 'Non-IID Defense',
    subtitle: '12 rounds - 6 clients - PID Control',
    description:
      'Real-world heterogeneous data distribution with adaptive PID-based client removal. Tests defense effectiveness against malicious clients in challenging conditions.',
    estimatedTime: '2-3 minutes',
    icon: '📊',
    tags: ['advanced', 'data-heterogeneity'],
    config: {
      num_of_rounds: 12,
      num_of_clients: 6,
      num_of_malicious_clients: 2,
      aggregation_strategy_keyword: 'pid',
      min_fit_clients: 6,
      min_evaluate_clients: 6,
      min_available_clients: 6,
      dataset_source: 'local',
      dataset_keyword: 'femnist_niid',
      model_type: 'cnn',
      use_llm: false,
      remove_clients: true,
      strict_mode: false,
      begin_removing_from_round: 2,
      training_subset_fraction: 0.5,
      num_of_client_epochs: 2,
      batch_size: 32,
      Kp: 1.0,
      Ki: 0.05,
      Kd: 0.05,
      num_std_dev: 2.2,
      show_plots: false,
      save_plots: true,
      save_csv: true,
      preserve_dataset: false,
      evaluate_metrics_aggregation_fn: 'weighted_average',
      save_attack_snapshots: true,
      attack_snapshot_format: 'pickle_and_visual',
      snapshot_max_samples: 6,
      attack_schedule: [
        {
          start_round: 1,
          end_round: 12,
          attack_type: 'gaussian_noise',
          target_noise_snr: 10,
          attack_ratio: 1.0,
          selection_strategy: 'specific',
          malicious_client_ids: [0, 1],
        },
      ],
    },
  },
  byzantine: {
    name: 'Byzantine Resilience',
    subtitle: '10 rounds - 7 clients - Krum',
    description:
      'Byzantine-robust aggregation defending against model poisoning attacks. Krum uses distance-based filtering to identify and exclude malicious weight updates.',
    estimatedTime: '2-3 minutes',
    icon: '⚔️',
    tags: ['intermediate', 'robust-aggregation', 'weight-poisoning'],
    config: {
      num_of_rounds: 10,
      num_of_clients: 7,
      num_of_malicious_clients: 2,
      aggregation_strategy_keyword: 'krum',
      num_krum_selections: 2,
      min_fit_clients: 7,
      min_evaluate_clients: 7,
      min_available_clients: 7,
      dataset_source: 'local',
      dataset_keyword: 'femnist_iid',
      model_type: 'cnn',
      use_llm: false,
      remove_clients: true,
      strict_mode: false,
      begin_removing_from_round: 2,
      training_subset_fraction: 0.5,
      num_of_client_epochs: 2,
      batch_size: 32,
      show_plots: false,
      save_plots: true,
      save_csv: true,
      preserve_dataset: false,
      evaluate_metrics_aggregation_fn: 'weighted_average',
      save_attack_snapshots: true,
      attack_snapshot_format: 'pickle_and_visual',
      snapshot_max_samples: 6,
      attack_schedule: [
        {
          start_round: 2,
          end_round: 8,
          attack_type: 'model_poisoning',
          poison_ratio: 0.2,
          magnitude: 0.5,
          selection_strategy: 'specific',
          malicious_client_ids: [0, 1],
        },
      ],
    },
  },
  medical: {
    name: 'Trimmed Mean Defense',
    subtitle: '10 rounds - 4 clients - Statistical Outlier Filtering',
    description:
      'Byzantine-robust aggregation defending against weight perturbation attacks. Trimmed mean filters outlier gradients from Byzantine clients.',
    estimatedTime: '2-3 minutes',
    icon: '🎯',
    tags: ['intermediate', 'robust-aggregation', 'weight-poisoning'],
    config: {
      num_of_rounds: 10,
      num_of_clients: 4,
      num_of_malicious_clients: 2,
      aggregation_strategy_keyword: 'trimmed_mean',
      trim_ratio: 0.25,
      min_fit_clients: 4,
      min_evaluate_clients: 4,
      min_available_clients: 4,
      dataset_source: 'local',
      dataset_keyword: 'femnist_iid',
      model_type: 'cnn',
      use_llm: false,
      batch_size: 32,
      remove_clients: false,
      begin_removing_from_round: 2,
      num_of_client_epochs: 2,
      training_subset_fraction: 0.5,
      show_plots: false,
      save_plots: true,
      save_csv: true,
      preserve_dataset: false,
      evaluate_metrics_aggregation_fn: 'weighted_average',
      save_attack_snapshots: true,
      attack_snapshot_format: 'pickle_and_visual',
      snapshot_max_samples: 6,
      attack_schedule: [
        {
          start_round: 1,
          end_round: 10,
          attack_type: 'byzantine_perturbation',
          perturbation_strength: 0.5,
          selection_strategy: 'specific',
          malicious_client_ids: [0, 1],
        },
      ],
    },
  },
  rfa: {
    name: 'Robust Federated Averaging',
    subtitle: '10 rounds - 4 clients - RFA',
    description:
      'Geometric median-based robust aggregation resisting gradient scaling attacks. RFA naturally filters extreme gradient magnifications without explicit detection.',
    estimatedTime: '2-3 minutes',
    icon: '🛡️',
    tags: ['intermediate', 'robust-aggregation', 'weight-poisoning'],
    config: {
      num_of_rounds: 10,
      num_of_clients: 4,
      num_of_malicious_clients: 2,
      aggregation_strategy_keyword: 'rfa',
      min_fit_clients: 4,
      min_evaluate_clients: 4,
      min_available_clients: 4,
      dataset_source: 'local',
      dataset_keyword: 'femnist_iid',
      model_type: 'cnn',
      use_llm: false,
      batch_size: 32,
      remove_clients: false,
      begin_removing_from_round: 1,
      num_of_client_epochs: 2,
      training_subset_fraction: 0.5,
      show_plots: false,
      save_plots: true,
      save_csv: true,
      preserve_dataset: false,
      evaluate_metrics_aggregation_fn: 'weighted_average',
      save_attack_snapshots: true,
      attack_snapshot_format: 'pickle_and_visual',
      snapshot_max_samples: 6,
      attack_schedule: [
        {
          start_round: 2,
          end_round: 8,
          attack_type: 'gradient_scaling',
          scale_factor: 15.0,
          selection_strategy: 'specific',
          malicious_client_ids: [0, 1],
        },
      ],
    },
  },
  adaptive_defense: {
    name: 'Adaptive Multi-Phase',
    subtitle: '15 rounds - 5 clients - Attack Schedule',
    description:
      'Advanced defense showcasing multiple attack types: data poisoning, weight poisoning, and gradient manipulation. PID controller adapts to evolving threats.',
    estimatedTime: '3-4 minutes',
    icon: '🔄',
    tags: ['advanced', 'defense', 'weight-poisoning'],
    config: {
      num_of_rounds: 15,
      num_of_clients: 5,
      num_of_malicious_clients: 2,
      aggregation_strategy_keyword: 'pid',
      min_fit_clients: 5,
      min_evaluate_clients: 5,
      min_available_clients: 5,
      dataset_source: 'local',
      dataset_keyword: 'femnist_iid',
      model_type: 'cnn',
      use_llm: false,
      remove_clients: true,
      strict_mode: false,
      begin_removing_from_round: 2,
      Kp: 1.0,
      Ki: 0.05,
      Kd: 0.05,
      num_std_dev: 2.0,
      training_subset_fraction: 0.5,
      num_of_client_epochs: 2,
      batch_size: 32,
      show_plots: false,
      save_plots: true,
      save_csv: true,
      preserve_dataset: false,
      evaluate_metrics_aggregation_fn: 'weighted_average',
      save_attack_snapshots: true,
      attack_snapshot_format: 'pickle_and_visual',
      snapshot_max_samples: 6,
      attack_schedule: [
        {
          start_round: 2,
          end_round: 5,
          attack_type: 'label_flipping',
          selection_strategy: 'specific',
          malicious_client_ids: [0],
        },
        {
          start_round: 6,
          end_round: 9,
          attack_type: 'model_poisoning',
          poison_ratio: 0.1,
          magnitude: 0.5,
          selection_strategy: 'specific',
          malicious_client_ids: [1],
        },
        {
          start_round: 10,
          end_round: 13,
          attack_type: 'gradient_scaling',
          scale_factor: 1.5,
          selection_strategy: 'specific',
          malicious_client_ids: [0, 1],
        },
      ],
    },
  },
};
